title: Manga in Print
description: typography
footer_text: "Copyright 2021 Emma Pollard "
header_feature_image: ../uploads/img_4809.jpg
header_text: MANGA IN PRINT
header_text_color: "#ffffff"
bannerheight: 100vh
navbarheight: 55px
logo: ../uploads/weblogo.png
favicon: ../uploads/weblogo.png
gridlayout: true
fixednavbar: false
upzoom: true
