title: Manga in Print
description: typography
footer_text: "Copyright 2021 Emma Pollard "
header_feature_image: ../uploads/img_4809-1-.jpg
header_text: ""
header_text_color: "#d3ff00"
bannerheight: 40vmax
navbarheight: 55px
logo: ../uploads/weblogo.png
favicon: ../uploads/weblogo.png
gridlayout: false
fixednavbar: false
upzoom: true
