title: Manga in Print
description: typography
footer_text: "Copyright 2021 Emma Pollard "
header_feature_image: ../uploads/img_4808.jpg
header_text: "MANGA IN PRINT: an exploration into the typography of physical manga"
header_text_color: "#ffffff"
bannerheight: 100vh
navbarheight: 55px
logo: ../uploads/weblogo.png
favicon: ../uploads/weblogo.png
gridlayout: true
fixednavbar: true
upzoom: true
items:
  - name: About me!
    siteurl: /aboutme
    tab: true
